name: iOS Pods Install

on: [push]

jobs:
  pod-install:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CocoaPods and dependencies
      run: |
        sudo gem install cocoapods
        cd ios
        pod install
